name: app

services:
  web1:
    image: nginx:latest
    ports:
      - "8081:80"

  web2:
    image: httpd
    ports:
      - "8082:80"

  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
